baseURL: "https://ebmorran.github.io"
languageCode: "en-us"
title: "Elizabeth Morran: Portfolio"
theme: hugo-profile
enableRobotsTXT: true


markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:

    #Dropdown menu
   # - identifier: dropdown
   #   title: Example dropdown menu
   #   name: Dropdown
   #   weight: 2
   # - identifier: dropdown1
   #   title: example dropdown 1
   #   name: example 1
   #   url: /#
   #   parent: dropdown
   #   weight: 1
   # - identifier: dropdown2
   #   title: example dropdown 2
   #   name: example 2
   #   url: /#
   #   parent: dropdown
   #   weight: 2

params:
  title: "Elizabeth Morran"
  description: Elizabeth Morran's creative portfolio.
  favicon: "/fav.png"


  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  color:
   textColor: 
   secondaryTextColor: 
   backgroundColor: 
   secondaryBackgroundColor: 
   primaryColor: "#b11226"
   secondaryColor: 

  darkmode:
   textColor: 
   secondaryTextColor:
   backgroundColor:
   secondaryBackgroundColor:
   primaryColor:
   secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: ""
    title: "Elizabeth Morran"
    subtitle: "Writing the “why.”"
    content: 'My aim as a writer is to integrate purpose and insight, illuminating the "what"
              for the sake of the "why."
              With a keen eye for clarity and structure, I develop effective 
              support content, persuasive email marketing copy and in-depth, SEO-tuned blog posts.
              <br><br>
              As a Customer Service Team Lead, I have three years of experience manifesting
              a consistent voice through concise, helpful content &mdash; in dozens of 
              customer emails and chat interactions per day.'
    image: /images/me.jpg
    # Make title & subtitle font slightly smaller.

  # projects
  projects:
    enable: true
    items:
      - title: Orchard Pixel launch email
        content: A marketing email I designed and wrote to announce Orchard's launch of the Pixel line of phones. I modified an EmailOnAcid template and edited royalty-free stock photos for visual unity. My goal was to distinguish the selling points of Pixels to our audience while capturing Orchard's unique value proposition. 
        image: /images/pixel-thumbnail.png
        featured:
          name: View
          link: /html_samples/pixel2.html
        badges:
           - "Email copywriting"
           - "Image editing"
           - "HTML"      

      - title: Orchard newsletter signup introduction
        content:  This is a post-signup email targeted at new subscribers to our mailing list. The goal here is to convey the value of our content, persuade the audience to open future emails and position Orchard as a knowledgeable expert in the smartphone industry.
        image: /images/newsletter-thumbnail.png
        featured:
          name: View
          link: /html_samples/our-story.html
        badges:
           - "Email copywriting"
           - "Image editing"
           - "Canva"
        # links:
        #  - icon: fab fa-github
        #    url: https://github.com/gurusabarish/converter

      - title: 4 Harmful Cat Myths We Need to Put To Rest
        content: Cats are some of the most popular pets in Canada, but even cat owners tend to misunderstand them. This piece scientifically debunks four common misconceptions about cats, to promote better human-feline relations.

        image: /images/cat-myths-thumbnail.png
        featured:
          name: View
          link: /pdf_samples/cat-myths.pdf
        badges:
          - "Blog writing"
          - "Research"    

      - title: 6 Crazy Superstitions From Around the World
        content: A short, quirky video highlighting local superstitions in Korea, Scotland,
                India, Brazil, Jamaica and Canada. An assignment completed in the Interactive Media Management program at Centennial College.
        image: /images/video-title-card-thumbnail.png
        featured:
          name: Learn more
          link: /work/superstitions-video/
        badges:
           - "Adobe Premiere"
           - "Adobe Illustrator"
           - "Storyboarding"
           - "Video directing"
        links:
          - icon: fab fa-youtube
            url: https://youtu.be/KmvonOKESzc
      
      - title: Orchard abandoned cart flow
        content: A series of abandoned cart re-engagement emails for Orchard, which I wrote and designed myself using HTML, CSS and Canva.
        image: /images/abandoned-cart-thumbnail.png
        featured:
          name: Learn more
          link: /work/abandoned-carts/
        badges:
           - "Email copywriting"
           - "HTML"
           - "Image editing"
           - "Canva"

      - title: 10 Early Childhood Behavior Management Strategies
        content: An informative article guiding child care providers to 10 useful strategies for encouraging good behavior and managing bad behavior at the daycare center.
        image: /images/phil-hearing-cylPETXS7is-unsplash.jpg
        featured:
          name: View
          link: /pdf_samples/10behavior.pdf
        badges:
           - "Blog writing"
           - "Research"      

      - title: Are Cats Antisocial? The Science of Purrfect Feline Relations
        content: Common perception holds that cats are cold, standoffish, selfish, even "furry
                  sociopaths." But cats, while not as outgoing as dogs, are far more companionable than many people believe. This piece explores the science behind how cats socialize, both with other cats and with humans.

        image: /images/cat-sociability-thumbnail.png
        featured:
          name: View
          link: /pdf_samples/cat-sociability-science.pdf
        badges:
          - "Blog writing"
          - "Research"              

      - title: 'JustGO: The carpool app for seniors'
        content: A group assignment I completed in the Interactive Media Management program at Centennial College. The prompt was to design an app for seniors. I was responsible for the app concept, research, user flow, onboarding sequence and the written content of the presentation. I also contributed to the wire frames.
        image: /images/justgo-thumbnail.png
        featured:
          name: View
          link: /pdf_samples/JustGO-compressed.pdf
        badges:
           - "UX design"
           - "Product design"
           - "User research"
           - "User flow"

      - title: Child Care Philosophy
        content: Every child care provider needs a guiding set of principles to determine their approach to early childhood education. This piece outlines some of the most common child care philosophies, and explains how to define your own.
        image: /images/gabe-pierce-mLqWFEtlIEs-unsplash.jpg
        featured:
          name: View
          link: /pdf_samples/childphilosophy.pdf
        badges:
          - "Blog writing"
          - "Research"   

      - title: 8 Benefits of Daycare
        content: Parents have many good reasons for wanting to send their child to a daycare, but they may be wondering how daycare benefits their child. In this piece, I explore 8 benefits of attending daycare for young children.
        image: /images/ryan-fields-Xz7MMD5tZwA-unsplash.jpg
        featured:
          name: View
          link: /pdf_samples/8benefits.pdf
        badges:
          - "Blog writing"
          - "Research"    

      - title: Orchard Paybright FAQ
        content: A FAQ page written to explain how financing works with Orchard.
        image: /images/kelly-sikkema-3-Tc_5LROrM-unsplash.jpg
        featured:
          name: View
          link: /pdf_samples/paybright.pdf
        badges:
          - "FAQ copywriting" 

      - title: How to Decorate a Daycare Center
        content: In this piece, I give child care providers actionable tips on how to decorate a well-organized, beautiful child care center that kids, parents and staff will love.
        image: /images/gautam-arora-78Ae6N7rNvI-unsplash.jpg
        featured:
          name: View
          link: /pdf_samples/decorate.pdf
        badges:
          - "Blog writing"
          - "Research"   

  #Contact
  contact:
    enable: true
    content: ""
    email: e.b.morran@gmail.com
    btnName: Email me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/ebmorran/
      linkedin: https://linkedin.com/in/emorran/
      facebook: https://www.facebook.com/ebmorran/
      # White FA icons. Open in new tabs.