baseURL: "https://ebmorran.github.io"
languageCode: "en-us"
title: "Elizabeth Morran"
theme: hugo-profile

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:

    #Dropdown menu
   # - identifier: dropdown
   #   title: Example dropdown menu
   #   name: Dropdown
   #   weight: 2
   # - identifier: dropdown1
   #   title: example dropdown 1
   #   name: example 1
   #   url: /#
   #   parent: dropdown
   #   weight: 1
   # - identifier: dropdown2
   #   title: example dropdown 2
   #   name: example 2
   #   url: /#
   #   parent: dropdown
   #   weight: 2

params:
  title: "Elizabeth Morran"
  description: Text about my cool site
  favicon: "/fav.png"
  # Separate browser favicon from this icon or find a new icon for this.

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor: 
  #   secondaryTextColor: 
  #   backgroundColor: 
  #   secondaryBackgroundColor: 
  #   primaryColor: 
  #   secondaryColor: 

  #   darkmode:
  #     textColor: 
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "hello"
    title: "Elizabeth Morran"
    subtitle: "Writing portfolio"
    content: "Lorem ipsum dolor sit amet."
    image: /images/me.jpg
    # Make title & subtitle font slightly smaller.

  # projects
  projects:
    enable: true
    items:
      - title: Orchard Pixel launch email
        content: A marketing email I designed (based on a modified EmailOnAcid template) to
                 announce Orchard's launch of the Pixel line of phones. I wrote
                 the copy and edited royalty-free stock photos. 
        image: /images/projects/profile.png
        featured:
          name: View
          link: https://hugo-profile.netlify.app
        badges:
           - "HTML"
        #   - "Bootstrap"
        #   - "Javascript"
      
      
      - title: 6 Crazy Superstitions From Around the World
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/video-title-card.png
        featured:
          name: Learn more
          link: https://hugo-profile.netlify.app
        badges:
           - "Adobe Premiere"
           - "Adobe Illustrator"
           - "Storyboarding"
           - "Video directing"
        links:
          - icon: fab fa-youtube
            url: https://youtu.be/KmvonOKESzc
        

      - title: Image Converter
        content:  A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter
      
      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: e.b.morran@gmail.com
    btnName: Email me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/ebmorran/
      linkedin: https://linkedin.com/in/emorran/
      facebook: https://www.facebook.com/ebmorran/
      # White FA icons. Open in new tabs.