baseURL: "https://ebmorran.github.io"
languageCode: "en-us"
title: "Elizabeth Morran: Portfolio"
theme: hugo-profile

# outputs:
#  home:
#    - "HTML"
#    - "RSS"
#    - "JSON"
#  page:
#    - "HTML"
#    - "RSS"

# Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
#    - identifier: about
#      name: About Me
#      title: About Me
#      url: /about
#      weight: 2
    - identifier: contact
      name: Contact
      title: Contact
      url: /#contact
      weight: 3
    - identifier: portfolio
      title: Portfolio
      name: Portfolio
      weight: 1
      url: /#portfolio
    - identifier: medavie
      title: Medavie Blue Cross
      name: Medavie Blue Cross
      url: /medavie-blue-cross
      parent: portfolio
      weight: 1
    - identifier: orchard
      title: Orchard
      name: Orchard
      url: /orchard
      parent: portfolio
      weight: 2
    - identifier: freelance
      title: Freelance & Student
      name: Freelance & Student
      url: /freelance
      parent: portfolio
      weight: 3

params:
  title: "Elizabeth Morran"
  description: Elizabeth Morran's creative portfolio.
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    textColor: 
    secondaryTextColor: 
    backgroundColor: 
    secondaryBackgroundColor: 
    primaryColor: "#b11226"
    secondaryColor: 
 

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Elizabeth Morran" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableAchievements: true
      disableContact: true

  # Hero
  hero:
    enable: true
    intro: ""
    title: "Elizabeth Morran"
    subtitle: "Content designer"
    content: "I'm a content designer with six years of experience as a professional writer and two in UX. I specialize in deep-diving into subject matter knowledge to create strategic content that demystifies complexity and orients users. I'm a true grammar nerd who's obsessed with the nuts and bolts of writing, and I love using AI and automations to free up human brains for human creativity."
    image: /images/me.jpg
    # Make title & subtitle font slightly smaller.
    bottomImage:
      enable: false
    roundImage: true # Make hero image circular | default false

  # About
  about:
    enable: false

  # Experience
  experience:
    enable: false

  # Education
  education:
    enable: false

  # Achievements
  achievements:
    enable: true
    title: "Portfolio"
    items:
      - title:
        content: 
        url: /medavie-blue-cross
        image: /images/logos/mbc-logo-en.png
      - title: 
        content: 
        url: /orchard
        image: /images/logos/orchard-logo.png
      - title: 
        content: 
        url: /freelance
        image: /images/logos/freelance.png

  # add company names to these
  # projects
  projects:
    enable: true
    title: "Featured projects"
    items:
      - title: Delisted providers in search
        content: "An update to Medavie's mobile provider search, adding a filter for delisted providers."
        image: /images/map-sample.png
        url: /medavie-blue-cross/delisted-providers/
      - title: Is it time for an upgrade?
        content: "Your guide to whether you need a new iPhone (or just a repair)."
        image: "/images/iphone-upgrade.jpg"
        url: /orchard/iphone-upgrade

  #Contact
  contact:
    enable: true
    title: Contact
    content: "Like my work? Give me a shout."
    btnName: Email me
    btnLink: mailto:e.b.morran@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    socialNetworks:
      github: https://github.com/ebmorran/
      linkedin: https://linkedin.com/in/emorran/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: false
      content: "min read"
    scrollprogress:
      enable: false

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved."
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
